##
## R package touch by Wenjie Wang, Yan Li, and Jun Yan
## Copyright (C) 2015-2019
##
## This file is part of the R package touch.
##
## The R package touch is free software: You can redistribute it and/or
## modify it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or any later
## version (at your option). See the GNU General Public License at
## <https://www.gnu.org/licenses/> for details.
##
## The R package touch is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
##

# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_split_string <- function(x) {
    .Call('_touch_rcpp_split_string', PACKAGE = 'touch', x)
}

rcpp_strsplit <- function(x) {
    .Call('_touch_rcpp_strsplit', PACKAGE = 'touch', x)
}

rcpp_strcat <- function(x) {
    .Call('_touch_rcpp_strcat', PACKAGE = 'touch', x)
}

rcpp_gem <- function(dx, which_map, cache = TRUE) {
    .Call('_touch_rcpp_gem', PACKAGE = 'touch', dx, which_map, cache)
}

init_gem_f17 <- function(keys, values) {
    invisible(.Call('_touch_init_gem_f17', PACKAGE = 'touch', keys, values))
}

init_gem_b17 <- function(keys, values) {
    invisible(.Call('_touch_init_gem_b17', PACKAGE = 'touch', keys, values))
}

init_gem_rf17 <- function(keys, values) {
    invisible(.Call('_touch_init_gem_rf17', PACKAGE = 'touch', keys, values))
}

init_gem_rb17 <- function(keys, values) {
    invisible(.Call('_touch_init_gem_rb17', PACKAGE = 'touch', keys, values))
}

init_gem_f18 <- function(keys, values) {
    invisible(.Call('_touch_init_gem_f18', PACKAGE = 'touch', keys, values))
}

init_gem_b18 <- function(keys, values) {
    invisible(.Call('_touch_init_gem_b18', PACKAGE = 'touch', keys, values))
}

init_gem_rf18 <- function(keys, values) {
    invisible(.Call('_touch_init_gem_rf18', PACKAGE = 'touch', keys, values))
}

init_gem_rb18 <- function(keys, values) {
    invisible(.Call('_touch_init_gem_rb18', PACKAGE = 'touch', keys, values))
}

