# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_split_string <- function(x) {
    .Call('_touch_rcpp_split_string', PACKAGE = 'touch', x)
}

rcpp_strsplit <- function(x) {
    .Call('_touch_rcpp_strsplit', PACKAGE = 'touch', x)
}

rcpp_strcat <- function(x) {
    .Call('_touch_rcpp_strcat', PACKAGE = 'touch', x)
}

rcpp_gem <- function(dx, which_map, cache = TRUE) {
    .Call('_touch_rcpp_gem', PACKAGE = 'touch', dx, which_map, cache)
}

init_gem_f17 <- function(keys, values) {
    invisible(.Call('_touch_init_gem_f17', PACKAGE = 'touch', keys, values))
}

init_gem_b17 <- function(keys, values) {
    invisible(.Call('_touch_init_gem_b17', PACKAGE = 'touch', keys, values))
}

init_gem_rf17 <- function(keys, values) {
    invisible(.Call('_touch_init_gem_rf17', PACKAGE = 'touch', keys, values))
}

init_gem_rb17 <- function(keys, values) {
    invisible(.Call('_touch_init_gem_rb17', PACKAGE = 'touch', keys, values))
}

init_gem_f18 <- function(keys, values) {
    invisible(.Call('_touch_init_gem_f18', PACKAGE = 'touch', keys, values))
}

init_gem_b18 <- function(keys, values) {
    invisible(.Call('_touch_init_gem_b18', PACKAGE = 'touch', keys, values))
}

init_gem_rf18 <- function(keys, values) {
    invisible(.Call('_touch_init_gem_rf18', PACKAGE = 'touch', keys, values))
}

init_gem_rb18 <- function(keys, values) {
    invisible(.Call('_touch_init_gem_rb18', PACKAGE = 'touch', keys, values))
}

